// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Threading;

namespace JFA.AdventureWorks.Entities
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class CreditCard
    {

        ///<summary>
        /// Primary key for CreditCard records.
        ///</summary>
        public int CreditCardId { get; set; }

        ///<summary>
        /// Credit card name.
        ///</summary>
        public string CardType { get; set; }

        ///<summary>
        /// Credit card number.
        ///</summary>
        public string CardNumber { get; set; }

        ///<summary>
        /// Credit card expiration month.
        ///</summary>
        public byte ExpMonth { get; set; }

        ///<summary>
        /// Credit card expiration year.
        ///</summary>
        public short ExpYear { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<PersonCreditCard> PersonCreditCards { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
        
        public CreditCard()
        {
            ModifiedDate = System.DateTime.Now;
            PersonCreditCards = new List<PersonCreditCard>();
            SalesOrderHeaders = new List<SalesOrderHeader>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
