// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // ErrorLog
    public partial class ErrorLogConfiguration : EntityTypeConfiguration<ErrorLog>
    {
        public ErrorLogConfiguration()
            : this("dbo")
        {
        }
 
        public ErrorLogConfiguration(string schema)
        {
            ToTable(schema + ".ErrorLog");
            HasKey(x => x.ErrorLogId);

            Property(x => x.ErrorLogId).HasColumnName("ErrorLogID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.ErrorTime).HasColumnName("ErrorTime").IsRequired().HasColumnType("datetime");
            Property(x => x.UserName).HasColumnName("UserName").IsRequired().HasColumnType("nvarchar").HasMaxLength(128);
            Property(x => x.ErrorNumber).HasColumnName("ErrorNumber").IsRequired().HasColumnType("int");
            Property(x => x.ErrorSeverity).HasColumnName("ErrorSeverity").IsOptional().HasColumnType("int");
            Property(x => x.ErrorState).HasColumnName("ErrorState").IsOptional().HasColumnType("int");
            Property(x => x.ErrorProcedure).HasColumnName("ErrorProcedure").IsOptional().HasColumnType("nvarchar").HasMaxLength(126);
            Property(x => x.ErrorLine).HasColumnName("ErrorLine").IsOptional().HasColumnType("int");
            Property(x => x.ErrorMessage).HasColumnName("ErrorMessage").IsRequired().HasColumnType("nvarchar").HasMaxLength(4000);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
