// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // Employee
    public partial class HumanResources_EmployeeConfiguration : EntityTypeConfiguration<HumanResources_Employee>
    {
        public HumanResources_EmployeeConfiguration()
            : this("HumanResources")
        {
        }
 
        public HumanResources_EmployeeConfiguration(string schema)
        {
            ToTable(schema + ".Employee");
            HasKey(x => x.BusinessEntityId);

            Property(x => x.BusinessEntityId).HasColumnName("BusinessEntityID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.NationalIdNumber).HasColumnName("NationalIDNumber").IsRequired().HasColumnType("nvarchar").HasMaxLength(15);
            Property(x => x.LoginId).HasColumnName("LoginID").IsRequired().HasColumnType("nvarchar").HasMaxLength(256);
            Property(x => x.OrganizationNode).HasColumnName("OrganizationNode").IsOptional().HasColumnType("hierarchyid").HasMaxLength(892);
            Property(x => x.OrganizationLevel).HasColumnName("OrganizationLevel").IsOptional().HasColumnType("smallint").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);
            Property(x => x.JobTitle).HasColumnName("JobTitle").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.BirthDate).HasColumnName("BirthDate").IsRequired().HasColumnType("date");
            Property(x => x.MaritalStatus).HasColumnName("MaritalStatus").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(1);
            Property(x => x.Gender).HasColumnName("Gender").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(1);
            Property(x => x.HireDate).HasColumnName("HireDate").IsRequired().HasColumnType("date");
            Property(x => x.SalariedFlag).HasColumnName("SalariedFlag").IsRequired().HasColumnType("bit");
            Property(x => x.VacationHours).HasColumnName("VacationHours").IsRequired().HasColumnType("smallint");
            Property(x => x.SickLeaveHours).HasColumnName("SickLeaveHours").IsRequired().HasColumnType("smallint");
            Property(x => x.CurrentFlag).HasColumnName("CurrentFlag").IsRequired().HasColumnType("bit");
            Property(x => x.Rowguid).HasColumnName("rowguid").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.ModifiedDate).HasColumnName("ModifiedDate").IsRequired().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Person_Person).WithOptional(b => b.HumanResources_Employee); // FK_Employee_Person_BusinessEntityID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
