// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vJobCandidate
    public partial class HumanResources_VJobCandidateConfiguration : EntityTypeConfiguration<HumanResources_VJobCandidate>
    {
        public HumanResources_VJobCandidateConfiguration()
            : this("HumanResources")
        {
        }
 
        public HumanResources_VJobCandidateConfiguration(string schema)
        {
            ToTable(schema + ".vJobCandidate");
            HasKey(x => new { x.JobCandidateId, x.ModifiedDate });

            Property(x => x.JobCandidateId).HasColumnName("JobCandidateID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.BusinessEntityId).HasColumnName("BusinessEntityID").IsOptional().HasColumnType("int");
            Property(x => x.Name46Prefix).HasColumnName("Name.Prefix").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Name46First).HasColumnName("Name.First").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Name46Middle).HasColumnName("Name.Middle").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Name46Last).HasColumnName("Name.Last").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Name46Suffix).HasColumnName("Name.Suffix").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Skills).HasColumnName("Skills").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Addr46Type).HasColumnName("Addr.Type").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Addr46Loc46CountryRegion).HasColumnName("Addr.Loc.CountryRegion").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.Addr46Loc46State).HasColumnName("Addr.Loc.State").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.Addr46Loc46City).HasColumnName("Addr.Loc.City").IsOptional().HasColumnType("nvarchar").HasMaxLength(100);
            Property(x => x.Addr46PostalCode).HasColumnName("Addr.PostalCode").IsOptional().HasColumnType("nvarchar").HasMaxLength(20);
            Property(x => x.EMail).HasColumnName("EMail").IsOptional().HasColumnType("nvarchar");
            Property(x => x.WebSite).HasColumnName("WebSite").IsOptional().HasColumnType("nvarchar");
            Property(x => x.ModifiedDate).HasColumnName("ModifiedDate").IsRequired().HasColumnType("datetime");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
