// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vJobCandidateEmployment
    public partial class HumanResources_VJobCandidateEmployment
    {
        public int JobCandidateId { get; set; } // JobCandidateID
        public DateTime? Emp46StartDate { get; set; } // Emp.StartDate
        public DateTime? Emp46EndDate { get; set; } // Emp.EndDate
        public string Emp46OrgName { get; set; } // Emp.OrgName
        public string Emp46JobTitle { get; set; } // Emp.JobTitle
        public string Emp46Responsibility { get; set; } // Emp.Responsibility
        public string Emp46FunctionCategory { get; set; } // Emp.FunctionCategory
        public string Emp46IndustryCategory { get; set; } // Emp.IndustryCategory
        public string Emp46Loc46CountryRegion { get; set; } // Emp.Loc.CountryRegion
        public string Emp46Loc46State { get; set; } // Emp.Loc.State
        public string Emp46Loc46City { get; set; } // Emp.Loc.City
        
        public HumanResources_VJobCandidateEmployment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
