// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Threading;

namespace JFA.AdventureWorks.Entities
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Location
    {

        ///<summary>
        /// Primary key for Location records.
        ///</summary>
        public short LocationId { get; set; }

        ///<summary>
        /// Location description.
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        /// Standard hourly cost of the manufacturing location.
        ///</summary>
        public decimal CostRate { get; set; }

        ///<summary>
        /// Work capacity (in hours) of the manufacturing location.
        ///</summary>
        public decimal Availability { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; }
        
        public Location()
        {
            CostRate = 0.00m;
            Availability = 0.00m;
            ModifiedDate = System.DateTime.Now;
            ProductInventories = new List<ProductInventory>();
            WorkOrderRoutings = new List<WorkOrderRouting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
