// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // Document
    public partial class Production_DocumentConfiguration : EntityTypeConfiguration<Production_Document>
    {
        public Production_DocumentConfiguration()
            : this("Production")
        {
        }
 
        public Production_DocumentConfiguration(string schema)
        {
            ToTable(schema + ".Document");
            HasKey(x => x.DocumentNode);

            Property(x => x.DocumentNode).HasColumnName("DocumentNode").IsRequired().HasColumnType("hierarchyid").HasMaxLength(892).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.DocumentLevel).HasColumnName("DocumentLevel").IsOptional().HasColumnType("smallint").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);
            Property(x => x.Title).HasColumnName("Title").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Owner).HasColumnName("Owner").IsRequired().HasColumnType("int");
            Property(x => x.FolderFlag).HasColumnName("FolderFlag").IsRequired().HasColumnType("bit");
            Property(x => x.FileName).HasColumnName("FileName").IsRequired().HasColumnType("nvarchar").HasMaxLength(400);
            Property(x => x.FileExtension).HasColumnName("FileExtension").IsRequired().HasColumnType("nvarchar").HasMaxLength(8);
            Property(x => x.Revision).HasColumnName("Revision").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(5);
            Property(x => x.ChangeNumber).HasColumnName("ChangeNumber").IsRequired().HasColumnType("int");
            Property(x => x.Status).HasColumnName("Status").IsRequired().HasColumnType("tinyint");
            Property(x => x.DocumentSummary).HasColumnName("DocumentSummary").IsOptional().HasColumnType("nvarchar");
            Property(x => x.Document).HasColumnName("Document").IsOptional().HasColumnType("varbinary");
            Property(x => x.Rowguid).HasColumnName("rowguid").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.ModifiedDate).HasColumnName("ModifiedDate").IsRequired().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.HumanResources_Employee).WithMany(b => b.Production_Documents).HasForeignKey(c => c.Owner); // FK_Document_Employee_Owner
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
