// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vProductAndDescription
    public partial class Production_VProductAndDescriptionConfiguration : EntityTypeConfiguration<Production_VProductAndDescription>
    {
        public Production_VProductAndDescriptionConfiguration()
            : this("Production")
        {
        }
 
        public Production_VProductAndDescriptionConfiguration(string schema)
        {
            ToTable(schema + ".vProductAndDescription");
            HasKey(x => new { x.ProductId, x.Name, x.ProductModel, x.CultureId, x.Description });

            Property(x => x.ProductId).HasColumnName("ProductID").IsRequired().HasColumnType("int");
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.ProductModel).HasColumnName("ProductModel").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CultureId).HasColumnName("CultureID").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(6);
            Property(x => x.Description).HasColumnName("Description").IsRequired().HasColumnType("nvarchar").HasMaxLength(400);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
