// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vProductModelInstructions
    public partial class Production_VProductModelInstructionConfiguration : EntityTypeConfiguration<Production_VProductModelInstruction>
    {
        public Production_VProductModelInstructionConfiguration()
            : this("Production")
        {
        }
 
        public Production_VProductModelInstructionConfiguration(string schema)
        {
            ToTable(schema + ".vProductModelInstructions");
            HasKey(x => new { x.ProductModelId, x.Name, x.Rowguid, x.ModifiedDate });

            Property(x => x.ProductModelId).HasColumnName("ProductModelID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.Instructions).HasColumnName("Instructions").IsOptional().HasColumnType("nvarchar");
            Property(x => x.LocationId).HasColumnName("LocationID").IsOptional().HasColumnType("int");
            Property(x => x.SetupHours).HasColumnName("SetupHours").IsOptional().HasColumnType("decimal").HasPrecision(9,4);
            Property(x => x.MachineHours).HasColumnName("MachineHours").IsOptional().HasColumnType("decimal").HasPrecision(9,4);
            Property(x => x.LaborHours).HasColumnName("LaborHours").IsOptional().HasColumnType("decimal").HasPrecision(9,4);
            Property(x => x.LotSize).HasColumnName("LotSize").IsOptional().HasColumnType("int");
            Property(x => x.Step).HasColumnName("Step").IsOptional().HasColumnType("nvarchar").HasMaxLength(1024);
            Property(x => x.Rowguid).HasColumnName("rowguid").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.ModifiedDate).HasColumnName("ModifiedDate").IsRequired().HasColumnType("datetime");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
