// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vPersonDemographics
    public partial class Sales_VPersonDemographicConfiguration : EntityTypeConfiguration<Sales_VPersonDemographic>
    {
        public Sales_VPersonDemographicConfiguration()
            : this("Sales")
        {
        }
 
        public Sales_VPersonDemographicConfiguration(string schema)
        {
            ToTable(schema + ".vPersonDemographics");
            HasKey(x => x.BusinessEntityId);

            Property(x => x.BusinessEntityId).HasColumnName("BusinessEntityID").IsRequired().HasColumnType("int");
            Property(x => x.TotalPurchaseYtd).HasColumnName("TotalPurchaseYTD").IsOptional().HasColumnType("money").HasPrecision(19,4);
            Property(x => x.DateFirstPurchase).HasColumnName("DateFirstPurchase").IsOptional().HasColumnType("datetime");
            Property(x => x.BirthDate).HasColumnName("BirthDate").IsOptional().HasColumnType("datetime");
            Property(x => x.MaritalStatus).HasColumnName("MaritalStatus").IsOptional().HasColumnType("nvarchar").HasMaxLength(1);
            Property(x => x.YearlyIncome).HasColumnName("YearlyIncome").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Gender).HasColumnName("Gender").IsOptional().HasColumnType("nvarchar").HasMaxLength(1);
            Property(x => x.TotalChildren).HasColumnName("TotalChildren").IsOptional().HasColumnType("int");
            Property(x => x.NumberChildrenAtHome).HasColumnName("NumberChildrenAtHome").IsOptional().HasColumnType("int");
            Property(x => x.Education).HasColumnName("Education").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Occupation).HasColumnName("Occupation").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.HomeOwnerFlag).HasColumnName("HomeOwnerFlag").IsOptional().HasColumnType("bit");
            Property(x => x.NumberCarsOwned).HasColumnName("NumberCarsOwned").IsOptional().HasColumnType("int");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
