// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace JFA.AdventureWorks.Entities
{
    // vStoreWithDemographics
    public partial class Sales_VStoreWithDemographicConfiguration : EntityTypeConfiguration<Sales_VStoreWithDemographic>
    {
        public Sales_VStoreWithDemographicConfiguration()
            : this("Sales")
        {
        }
 
        public Sales_VStoreWithDemographicConfiguration(string schema)
        {
            ToTable(schema + ".vStoreWithDemographics");
            HasKey(x => new { x.BusinessEntityId, x.Name });

            Property(x => x.BusinessEntityId).HasColumnName("BusinessEntityID").IsRequired().HasColumnType("int");
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.AnnualSales).HasColumnName("AnnualSales").IsOptional().HasColumnType("money").HasPrecision(19,4);
            Property(x => x.AnnualRevenue).HasColumnName("AnnualRevenue").IsOptional().HasColumnType("money").HasPrecision(19,4);
            Property(x => x.BankName).HasColumnName("BankName").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.BusinessType).HasColumnName("BusinessType").IsOptional().HasColumnType("nvarchar").HasMaxLength(5);
            Property(x => x.YearOpened).HasColumnName("YearOpened").IsOptional().HasColumnType("int");
            Property(x => x.Specialty).HasColumnName("Specialty").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.SquareFeet).HasColumnName("SquareFeet").IsOptional().HasColumnType("int");
            Property(x => x.Brands).HasColumnName("Brands").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.Internet).HasColumnName("Internet").IsOptional().HasColumnType("nvarchar").HasMaxLength(30);
            Property(x => x.NumberEmployees).HasColumnName("NumberEmployees").IsOptional().HasColumnType("int");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
