// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Threading;

namespace JFA.AdventureWorks.Entities
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class SpecialOffer
    {

        ///<summary>
        /// Primary key for SpecialOffer records.
        ///</summary>
        public int SpecialOfferId { get; set; }

        ///<summary>
        /// Discount description.
        ///</summary>
        public string Description { get; set; }

        ///<summary>
        /// Discount precentage.
        ///</summary>
        public decimal DiscountPct { get; set; }

        ///<summary>
        /// Discount type category.
        ///</summary>
        public string Type { get; set; }

        ///<summary>
        /// Group the discount applies to such as Reseller or Customer.
        ///</summary>
        public string Category { get; set; }

        ///<summary>
        /// Discount start date.
        ///</summary>
        public DateTime StartDate { get; set; }

        ///<summary>
        /// Discount end date.
        ///</summary>
        public DateTime EndDate { get; set; }

        ///<summary>
        /// Minimum discount percent allowed.
        ///</summary>
        public int MinQty { get; set; }

        ///<summary>
        /// Maximum discount percent allowed.
        ///</summary>
        public int? MaxQty { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }
        
        public SpecialOffer()
        {
            DiscountPct = 0.00m;
            MinQty = 0;
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            SpecialOfferProducts = new List<SpecialOfferProduct>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
