// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Threading;

namespace JFA.AdventureWorks.Entities
{
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class UnitMeasure
    {

        ///<summary>
        /// Primary key.
        ///</summary>
        public string UnitMeasureCode { get; set; }

        ///<summary>
        /// Unit of measure description.
        ///</summary>
        public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; }
        public virtual ICollection<Product> Products_SizeUnitMeasureCode { get; set; }
        public virtual ICollection<Product> Products_WeightUnitMeasureCode { get; set; }
        public virtual ICollection<ProductVendor> ProductVendors { get; set; }
        
        public UnitMeasure()
        {
            ModifiedDate = System.DateTime.Now;
            BillOfMaterials = new List<BillOfMaterial>();
            Products_SizeUnitMeasureCode = new List<Product>();
            Products_WeightUnitMeasureCode = new List<Product>();
            ProductVendors = new List<ProductVendor>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
